### ISSUE TITLE
No config file

### ISSUE THREAD

**Issue by nikitatrifan** [drenther/next-pwa#1]
Hey.

Pretty excited to run your app and see the result, but there is an error:
```
> Failed to build
{ Error: (client) ./utils/apiCalls.js
Module not found: Error: Can't resolve './config' in '/next-pwa/utils'
```

**Comment by drenther** [comment]
You can check the **[Setting up data fetching logic](https://able.bio/drenther/building-a-progressive-web-app-with-nextjs-part-i--00edasw#Setting_up_data_fetching_logic)** section in the first part of the tutorial. There I have mentioned that the config.js file is a file that is not committed to git as it contains the API key. It is kind of our .env file.

You can get yourself a [TMDB](https://www.themoviedb.org/en) API key and create the config.js file yourself where you export out the API_KEY variable from it.

I hope this solves the issue for you.
