### ISSUE TITLE
Error when reloading movie detail and coming from home page

### ISSUE THREAD

**Issue by loicbourg** [drenther/next-pwa#3]
Hello,

thanks for this next pwa example !

I have something which doesn't work, but i don't know if it's normal:

When I go to the home page
And I go to the movie page
And i set my browser to offline mode
And i click on the home page link
And i click on the home page link
Then Everything is working fine, the home page get displayed even when the browser is offline

But: 
When I go to the home page
And I go to the movie page
And i set my browser to offline mode
And i click on the home page link
And i click on the same movie page
And i Reload the page (F5)
Then I have a network error displayed on the browser.

Since I have already visited this page, shouldn't it be accessible offline like when i click on the link ?

I have uploaded a video here: https://ufile.io/se5vq to better explain the problem

**Comment by drenther** [comment]
Sorry for the late reply. I did not notice this issue being filed earlier. Are you still facing the issue?

**Comment by loicbourg** [comment]
Hello,

No problem for the late reply, i was just curious if you knew this behavior when browsing the app offline and if a workaround was possible.

The issue is still present, and i reuploaded the video here: https://ufile.io/fqmjxs6c

**Comment by drenther** [comment]
I haven't experienced that issue earlier. But, I haven't tested it
recently. Have you tried debugging it by tinkering with the workbox setup?
Anything to do with the offline capabilities will have to be regarding that.

I am unable to access the video file though.

**Comment by drenther** [comment]
Closing this issue.
