### ISSUE TITLE
Site is not running up

### ISSUE THREAD

**Issue by findelallc** [drenther/next-pwa#5]
I tried following installation guide but it doesn't work,I also added movie api key in config.json to load .Is there any config missing I am?

![Screenshot from 2019-08-28 00-11-02](https://user-images.githubusercontent.com/8926058/63798847-72002e00-c928-11e9-8175-cbab897ad694.png)

**Comment by drenther** [comment]
Can you please provide more details?

**Comment by findelallc** [comment]
It's working with another solution likewise [this](https://github.com/shadowwalker/next-pwa)
